### ISSUE TITLE
where is fg being used

### ISSUE THREAD

**Issue by mxmxlwlw** [skoppula/dorefa-net#1]
Hi,
    I can see where fw and fa being used, but where is fg being used?

**Comment by skoppula** [comment]
It's not.

**Comment by mxmxlwlw** [comment]
Then how can I use it? And I'm curious how to speed up the training, because of using tensorflow backend. It can't speed up using quantization algorithm

**Comment by skoppula** [comment]
Check out the original DoReFa source.

**Comment by skoppula** [comment]
Also, changing the bitwidth of the gradient is unlikely to speed up your training because of fixed width operations on your hardware.

**Comment by mxmxlwlw** [comment]
Thank you!
